### ISSUE TITLE
Default deletion of older assets

### ISSUE THREAD

**Issue by pwaller** [robertkrimen/gphr#2]
Can I ask why the destructive operation of "deleting old assets" is the default?

If you wanted this behaviour, it would be easy enough to turn it on, but I don't know why I would want this behaviour from the get-go.

Could you consider changing the default? I just accidentally blatted lots of binaries, which I wasn't expecting.

**Comment by pwaller** [comment]
Hm, I can't even make an alias `alias gphr='gphr -keep'` to make it safe in my environment.

**Comment by robertkrimen** [comment]
I'll change the `-keep` default to be `true`, which should prevent the purge from happening.

**Comment by pwaller** [comment]
I see you made a branch, but it hasn't been merged or released. Any chance of cooking a release? Thanks!

**Comment by pwaller** [comment]
Ping.

**Comment by pwaller** [comment]
I've moved to using `hub release`. https://github.com/github/hub
